# Generates a self-contained bash submit_all_<dataset_id>.sh, written
# alongside the _rslurm_<jobname>/ directories in
# slurm_bundles/<dataset_id>/ so it travels with the bundle (including into
# a squashfs archive built from that directory).
#
# This is deliberately thin: every job family's resource requirements
# (mem/cpus/time/array size) already live in that family's own
# rslurm-generated submit.sh, and the container + squashfs bind are baked
# into that same submit.sh's `apptainer run ...` invocation (see
# R/lib/submit.R::build_apptainer_rscript_path() and
# config/rslurm_templates/submit_sh.txt). submit_all_<dataset_id>.sh
# doesn't need to know or duplicate any of that; it just needs to find
# each `_rslurm_*/submit.sh` inside a temporary local mount of the archive
# and submit it with the two things every family needs but can't know at
# bundle-build time (since the bundle moves to a different machine):
# `SQUASHFS_PATH` (referenced inside each submit.sh's `apptainer run -B
# "$SQUASHFS_PATH":...` invocation) and `RSLURM_OUTPUT_DIR` (read by
# slurm_run.R). Both are plain shell `export`s in this script, not passed
# via `sbatch --export=` -- Slurm propagates the submitting shell's
# environment to the job by default, so nothing extra is needed there.
#
# Job families are discovered dynamically at submission time (by listing
# `_rslurm_*` directories inside a temporary mount of the archive), not
# baked in at generation time -- so there's no per-family manifest to keep
# in sync. The generated script's content only depends on `dataset_id`
# (for default naming/comments), so regenerating it after every
# setup_*_rslurm.R run is just a convenience, not a correctness
# requirement.

.submit_all_template <- function(dataset_id) {
  sprintf('#!/usr/bin/env bash
# Generated by R/lib/submit_all_script.R -- submits every job family
# (every _rslurm_<jobname>/submit.sh) found inside this squashfs archive,
# or just one if --only is given. Intended to be copied out of a
# mounted/extracted archive and run from wherever you want results to
# land, e.g.:
#   cd /scratch/mblab/chasem/latent_factor_eda
#   ./submit_all_%s.sh %s.sqfs                          # every job family
#   ./submit_all_%s.sh %s.sqfs --only _rslurm_wgcna_grid # just this one
#   ./submit_all_%s.sh %s.sqfs /some/results/dir --only _rslurm_wgcna_grid
set -euo pipefail

usage() { echo "Usage: $0 <path-to-squashfs-archive> [results-dir] [--only _rslurm_<jobname>]" >&2; exit 1; }
[ $# -ge 1 ] || usage

# --only is a flag (not a positional argument) specifically so it cannot
# be silently misinterpreted as results-dir if passed in the wrong slot --
# an earlier positional-only version of this script had exactly that trap.
ARCHIVE=""
RESULTS_ARG=""
JOB_FILTER=""
while [ $# -gt 0 ]; do
  case "$1" in
    --only)
      [ $# -ge 2 ] || usage
      JOB_FILTER="$2"
      shift 2
      ;;
    --only=*)
      JOB_FILTER="${1#--only=}"
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      if [ -z "$ARCHIVE" ]; then
        ARCHIVE="$1"
      elif [ -z "$RESULTS_ARG" ]; then
        RESULTS_ARG="$1"
      else
        usage
      fi
      shift
      ;;
  esac
done
[ -n "$ARCHIVE" ] || usage

export SQUASHFS_PATH="$(realpath "$ARCHIVE")"
RESULTS_DIR="$(realpath -m "${RESULTS_ARG:-$(pwd)/%s_results}")"
mkdir -p "$RESULTS_DIR"

echo "squashfs archive: $SQUASHFS_PATH"
echo "results will land in: $RESULTS_DIR"
[ -n "$JOB_FILTER" ] && echo "only submitting: $JOB_FILTER"

# Mounted here (on THIS host, uncontainerized -- squashfuse works fine
# outside a container) only long enough to discover and submit each
# existing family submit.sh (already has the right #SBATCH resource
# directives and apptainer invocation -- nothing to duplicate). Tries
# squashfuse first (unprivileged, common on HPC), falls back to a loop
# mount (needs root).
SUBMIT_MOUNT="$(mktemp -d)"
squashfuse "$SQUASHFS_PATH" "$SUBMIT_MOUNT" 2>/dev/null || mount -t squashfs -o loop "$SQUASHFS_PATH" "$SUBMIT_MOUNT"
trap \'fusermount -u "$SUBMIT_MOUNT" 2>/dev/null || umount "$SUBMIT_MOUNT" 2>/dev/null || true; rmdir "$SUBMIT_MOUNT" 2>/dev/null || true\' EXIT

if [ -n "$JOB_FILTER" ] && [ ! -d "$SUBMIT_MOUNT/$JOB_FILTER" ]; then
  echo "error: $JOB_FILTER not found in this archive" >&2
  echo "available: $(cd "$SUBMIT_MOUNT" && echo _rslurm_*)" >&2
  exit 1
fi

shopt -s nullglob
matched=0
for job_dir in "$SUBMIT_MOUNT"/_rslurm_*; do
  [ -f "$job_dir/submit.sh" ] || continue
  jobdir_name="$(basename "$job_dir")"
  if [ -n "$JOB_FILTER" ] && [ "$jobdir_name" != "$JOB_FILTER" ]; then
    continue
  fi
  matched=$((matched + 1))
  jobname="${jobdir_name#_rslurm_}"
  mkdir -p "$RESULTS_DIR/$jobname/logs"
  echo "submitting $jobname ..."
  export RSLURM_OUTPUT_DIR="$RESULTS_DIR/$jobname"
  sbatch --output="$RESULTS_DIR/$jobname/logs/%%a.out" "$job_dir/submit.sh"
done

[ "$matched" -gt 0 ] || { echo "error: no matching _rslurm_*/submit.sh found" >&2; exit 1; }
', dataset_id, dataset_id, dataset_id, dataset_id, dataset_id, dataset_id, dataset_id)
}

#' Write `<bundle_dir>/submit_all_<dataset_id>.sh`. Safe to call repeatedly
#' (e.g. once at the end of every setup_*_rslurm.R script) -- content only
#' depends on `dataset_id`, so this always (re)writes the same thing.
write_submit_all_script <- function(dataset_id, bundle_dir) {
  dir.create(bundle_dir, recursive = TRUE, showWarnings = FALSE)
  out_path <- file.path(bundle_dir, paste0("submit_all_", dataset_id, ".sh"))
  writeLines(.submit_all_template(dataset_id), out_path)
  Sys.chmod(out_path, "0755")
  message("Wrote ", out_path)
  invisible(out_path)
}
