# Generates a self-contained bash submit_all_<dataset_id>.sh, written
# alongside the _rslurm_<jobname>/ directories in
# slurm_bundles/<dataset_id>/ so it travels with the bundle (e.g. via a
# plain `rsync`/`scp` of the whole directory to the cluster -- no
# packaging step at all).
#
# This is deliberately thin: every job family's resource requirements
# (mem/cpus/time/array size) already live in that family's own
# rslurm-generated submit.sh, and the container + bundle-directory bind
# are baked into that same submit.sh's `apptainer run ...` invocation (see
# R/lib/submit.R::build_apptainer_rscript_path() and
# config/rslurm_templates/submit_sh.txt). submit_all_<dataset_id>.sh
# doesn't need to know or duplicate any of that; it just needs to find
# each `_rslurm_*/submit.sh` directly inside the bundle directory and
# submit it with the two things every family needs but can't know at
# bundle-build time (since the bundle moves to a different machine):
# `RSLURM_BUNDLE_DIR` (referenced inside each submit.sh's `apptainer run
# -B "$RSLURM_BUNDLE_DIR":...` invocation) and `RSLURM_OUTPUT_DIR` (read
# by slurm_run.R). Both are plain shell `export`s in this script, not
# passed via `sbatch --export=` -- Slurm propagates the submitting
# shell's environment to the job by default, so nothing extra is needed
# there.
#
# Job families are discovered dynamically at submission time (by listing
# `_rslurm_*` directories inside the bundle directory), not baked in at
# generation time -- so there's no per-family manifest to keep in sync.
# The generated script's content only depends on `dataset_id` (for
# default naming/comments), so regenerating it after every
# setup_*_rslurm.R run is just a convenience, not a correctness
# requirement.

.submit_all_template <- function(dataset_id) {
  sprintf('#!/usr/bin/env bash
# Generated by R/lib/submit_all_script.R -- submits every job family
# (every _rslurm_<jobname>/submit.sh) found inside this bundle directory,
# or just one if --only is given. No packaging step at all -- just copy
# the whole slurm_bundles/%s/ directory to wherever you want to submit
# from (e.g. via rsync/scp) and run this script pointing at it, e.g.:
#   rsync -av slurm_bundles/%s/ user@cluster:/scratch/mblab/chasem/latent_factor_eda/%s_bundle/
#   ssh user@cluster
#   cd /scratch/mblab/chasem/latent_factor_eda
#   ./%s_bundle/submit_all_%s.sh ./%s_bundle                          # every job family
#   ./%s_bundle/submit_all_%s.sh ./%s_bundle --only _rslurm_wgcna_grid # just this one
#   ./%s_bundle/submit_all_%s.sh ./%s_bundle /some/results/dir --only _rslurm_wgcna_grid
set -euo pipefail

usage() { echo "Usage: $0 <path-to-bundle-directory> [results-dir] [--only _rslurm_<jobname>]" >&2; exit 1; }
[ $# -ge 1 ] || usage

# --only is a flag (not a positional argument) specifically so it cannot
# be silently misinterpreted as results-dir if passed in the wrong slot --
# an earlier positional-only version of this script had exactly that trap.
BUNDLE_DIR=""
RESULTS_ARG=""
JOB_FILTER=""
while [ $# -gt 0 ]; do
  case "$1" in
    --only)
      [ $# -ge 2 ] || usage
      JOB_FILTER="$2"
      shift 2
      ;;
    --only=*)
      JOB_FILTER="${1#--only=}"
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      if [ -z "$BUNDLE_DIR" ]; then
        BUNDLE_DIR="$1"
      elif [ -z "$RESULTS_ARG" ]; then
        RESULTS_ARG="$1"
      else
        usage
      fi
      shift
      ;;
  esac
done
[ -n "$BUNDLE_DIR" ] || usage
[ -d "$BUNDLE_DIR" ] || { echo "error: $BUNDLE_DIR is not a directory" >&2; exit 1; }

export RSLURM_BUNDLE_DIR="$(realpath "$BUNDLE_DIR")"
RESULTS_DIR="$(realpath -m "${RESULTS_ARG:-$(pwd)/%s_results}")"
mkdir -p "$RESULTS_DIR"

echo "bundle directory: $RSLURM_BUNDLE_DIR"
echo "results will land in: $RESULTS_DIR"
[ -n "$JOB_FILTER" ] && echo "only submitting: $JOB_FILTER"

if [ -n "$JOB_FILTER" ] && [ ! -d "$RSLURM_BUNDLE_DIR/$JOB_FILTER" ]; then
  echo "error: $JOB_FILTER not found in $RSLURM_BUNDLE_DIR" >&2
  echo "available: $(cd "$RSLURM_BUNDLE_DIR" && echo _rslurm_*)" >&2
  exit 1
fi

shopt -s nullglob
matched=0
for job_dir in "$RSLURM_BUNDLE_DIR"/_rslurm_*; do
  [ -f "$job_dir/submit.sh" ] || continue
  jobdir_name="$(basename "$job_dir")"
  if [ -n "$JOB_FILTER" ] && [ "$jobdir_name" != "$JOB_FILTER" ]; then
    continue
  fi
  matched=$((matched + 1))
  jobname="${jobdir_name#_rslurm_}"
  mkdir -p "$RESULTS_DIR/$jobname/logs"
  echo "submitting $jobname ..."
  export RSLURM_OUTPUT_DIR="$RESULTS_DIR/$jobname"
  sbatch --output="$RESULTS_DIR/$jobname/logs/%%a.out" "$job_dir/submit.sh"
done

[ "$matched" -gt 0 ] || { echo "error: no matching _rslurm_*/submit.sh found" >&2; exit 1; }
', dataset_id, dataset_id, dataset_id, dataset_id, dataset_id, dataset_id, dataset_id, dataset_id, dataset_id,
   dataset_id, dataset_id, dataset_id, dataset_id)
}

#' Write `<bundle_dir>/submit_all_<dataset_id>.sh`. Safe to call repeatedly
#' (e.g. once at the end of every setup_*_rslurm.R script) -- content only
#' depends on `dataset_id`, so this always (re)writes the same thing.
write_submit_all_script <- function(dataset_id, bundle_dir) {
  dir.create(bundle_dir, recursive = TRUE, showWarnings = FALSE)
  out_path <- file.path(bundle_dir, paste0("submit_all_", dataset_id, ".sh"))
  writeLines(.submit_all_template(dataset_id), out_path)
  Sys.chmod(out_path, "0755")
  message("Wrote ", out_path)
  invisible(out_path)
}
